### ISSUE TITLE
'DataLoaderRaw' object has no attribute 'dataset'

### ISSUE THREAD

**Issue by carloscaetano** [ruotianluo/self-critical.pytorch#164]
Got this error while trying to run eval.py

Traceback (most recent call last):
  File "eval.py", line 110, in <module>
    loader.dataset.ix_to_word = infos['vocab']
AttributeError: 'DataLoaderRaw' object has no attribute 'dataset'

**Comment by ruotianluo** [comment]
To use dataloaderraw, you can replace with loader.ix_to_word = infos['vocab'].

I will fix this problem

**Comment by mememimis** [comment]
There are some little issues with the dataloader as well. For example    data = next(dataiterator) , dataiterator is not defined. As well when you use more than than 0 workers  is line self.iters[split]._send_idx breaks with send_idx as unresolved reference.

**Comment by ruotianluo** [comment]
Thanks for pointing this our

**Comment by sohamirian** [comment]
I still have the same problem. What can I do?

**Comment by ruotianluo** [comment]
@mememimis For the _send_idx, are you using pytorch1.3+

**Comment by sohamirian** [comment]
Dear Ruotian, what version should I use?

**Comment by ruotianluo** [comment]
What problem did you see?

**Comment by ruotianluo** [comment]
1.3+ is required.

**Comment by mememimis** [comment]
I'm using pytorch 1.3.1

**Comment by sohamirian** [comment]
I installed torch 1.3.1 but still I have the same problem.
Traceback (most recent call last):
  File "eval.py", line 108, in <module>
    loader.dataset.ix_to_word = infos['vocab']
AttributeError: 'DataLoaderRaw' object has no attribute 'dataset'

**Comment by sohamirian** [comment]
Dear Ruotianluo,

Thank you so much for all your prompt responses.
I installed torch 1.3.1 but still, I have the same problem.
Traceback (most recent call last):
  File "eval.py", line 108, in <module>
    loader.dataset.ix_to_word = infos['vocab']
AttributeError: 'DataLoaderRaw' object has no attribute 'dataset'

Sincerely,
Soheyla Amirian

**Comment by ruotianluo** [comment]
@sohamirian This should be fixed now (The solution was at the top too.)

**Comment by sohamirian** [comment]
Thank you so much!
It worked.

**Comment by mememimis** [comment]
the _send_idx still persists in my case. I installed, uninstalled pytorch but still.

**Comment by wolfgodAmaterasu** [comment]
> the _send_idx still persists in my case. I installed, uninstalled pytorch but still.
Hello, I meet the same problem. Do you have a solution to this problem? Thank you
